name: camera
frame_id: "vimba_front_right_center"
ip: '10.42.7.52'
guid: ''
use_measurement_time: false
ptp_offset: 0
publish_compressed: true
feature/AcquisitionFrameCount: 1
feature/AcquisitionFrameRateAbs: 20.0
feature/AcquisitionMode: Continuous
feature/ActionDeviceKey: 0
feature/ActionGroupKey: 0
feature/ActionGroupMask: 0
feature/ActionSelector: 0
feature/BalanceRatioAbs: 2.0
feature/BalanceRatioSelector: Red
feature/BalanceWhiteAuto: 'Off'
feature/BalanceWhiteAutoAdjustTol: 5
feature/BalanceWhiteAutoRate: 100
feature/BandwidthControlMode: StreamBytesPerSecond
feature/BinningHorizontal: 1
feature/BinningVertical: 1
feature/BlackLevel: 50.0
feature/BlackLevelSelector: All
feature/ChunkModeActive: false
feature/ColorTransformationMode: 'Off'
feature/ColorTransformationSelector: RGBtoRGB
feature/ColorTransformationValue: 1.0
feature/ColorTransformationValueSelector: Gain00
feature/DSPSubregionBottom: 600
feature/DSPSubregionLeft: 4
feature/DSPSubregionRight: 1032
feature/DSPSubregionTop: 300
feature/DecimationHorizontal: 4
feature/DecimationVertical: 4
feature/DeviceTemperatureSelector: Main
feature/DeviceUserID: ''
feature/EventNotification: 'Off'
feature/EventSelector: AcquisitionStart
feature/EventsEnable1: 0
feature/ExposureAuto: 'Continuous'
feature/ExposureAutoAdjustTol: 5
feature/ExposureAutoAlg: FitRange
feature/ExposureAutoMax: 30000
feature/ExposureAutoMin: 29
feature/ExposureAutoOutliers: 1000
feature/ExposureAutoRate: 100
feature/ExposureAutoTarget: 50
feature/ExposureMode: Timed
feature/ExposureTimeAbs: 24973.0
# feature/GVCPCmdRetries: 5
# feature/GVCPCmdTimeout: 250
# feature/GVSPBurstSize: 1
# feature/GVSPDriver: Socket
# feature/GVSPHostReceiveBufferSize: 10240
# feature/GVSPMaxLookBack: 30
# feature/GVSPMaxRequests: 1
# feature/GVSPMaxWaitSize: 100
# feature/GVSPMissingSize: 256
# feature/GVSPPacketSize: 9014
# feature/GVSPTiltingSize: 100
# feature/GVSPTimeout: 70
feature/Gain: 6.0
feature/GainAuto: 'Continuous'
feature/GainAutoAdjustTol: 5
feature/GainAutoMax: 32.0
feature/GainAutoMin: 0.0
feature/GainAutoOutliers: 100
feature/GainAutoRate: 50
feature/GainAutoTarget: 50
feature/GainSelector: All
feature/Gamma: 1.0
# feature/GevHeartbeatInterval: 1450
# feature/GevHeartbeatTimeout: 3000
# feature/GevSCPSPacketSize: 9014
feature/Height: 384
feature/Hue: 0.0
feature/LUTEnable: false
feature/LUTIndex: 0
feature/LUTMode: Luminance
feature/LUTSelector: LUT1
feature/LUTValue: 4095
feature/MulticastEnable: false
feature/MulticastIPAddress: 4026470193
feature/OffsetX: 0
feature/OffsetY: 0
feature/PixelFormat: BayerRG8
feature/PtpAcquisitionGateTime: 0
feature/PtpMode: 'Slave'
feature/RecorderPreEventCount: 0
feature/ReverseX: false
feature/ReverseY: false
feature/Saturation: 1.0
feature/StreamBufferHandlingMode: Default
feature/StreamBytesPerSecond: 115000000
feature/StreamFrameRateConstrain: true
feature/StreamHoldEnable: 'Off'
feature/StrobeDelay: 0
feature/StrobeDuration: 0
feature/StrobeDurationMode: Source
feature/StrobeSource: FrameTrigger
feature/SyncInGlitchFilter: 0
feature/SyncInSelector: SyncIn1
feature/SyncOutLevels: 0
feature/SyncOutPolarity: Normal
feature/SyncOutSelector: SyncOut1
feature/SyncOutSource: Exposing
feature/TriggerActivation: RisingEdge
feature/TriggerDelayAbs: 0.0
feature/TriggerMode: 'On'
feature/TriggerOverlap: 'Off'
feature/TriggerSelector: FrameStart
feature/TriggerSource: FixedRate
feature/UserSetDefaultSelector: Default
feature/UserSetSelector: Default
feature/Width: 516